<?php

namespace App\Traits;

use App\Models\CastMember;
use App\Models\Episode;
use App\Models\Movie;
use App\Models\Season;
use App\Models\Series;

trait CastMemberHelpers {
    private function getCastMember($cast_member) {
        return CastMember::firstOrCreate(
            ['id' => $cast_member->id],
            [
                'name' => $cast_member->name,
                'original_name' => $cast_member->original_name,
                'profile_path' => $cast_member->profile_path ?: null,
            ]
        );
    }

    /**
     * Attach a TMDB credits payload to a Movie/Series/Season/Episode.
     *
     * Was 3 queries per cast member (an exists() check, a firstOrCreate, an attach).
     * With cast_member_episode already past 250k rows that dominated ingestion, so
     * the membership check and the pivot insert are each done once for the whole
     * payload. Creating the people themselves stays row-by-row on purpose:
     * cast_members.slug is unique and generated by Spatie's HasSlug on the model's
     * `creating` event, which a bulk upsert() would bypass, inserting blank slugs.
     */
    private function attachCastMemberToModel($model, $cast_members) {
        // TMDB can credit the same person twice in one payload. The id-keyed
        // $pivotData array below already collapses those; deduping here just avoids
        // a redundant getCastMember() lookup per repeat.
        $cast_members = collect($cast_members)->unique('id')->values();

        if ($cast_members->isEmpty()) {
            return;
        }

        $alreadyAttached = $model->cast_members()->pluck('cast_members.id')->all();

        $incoming = $cast_members
            ->reject(fn ($cast_member) => in_array($cast_member->id, $alreadyAttached))
            ->values();

        if ($incoming->isEmpty()) {
            return;
        }

        $pivotData = [];

        foreach ($incoming as $cast_member) {
            $member = $this->getCastMember($cast_member);

            $pivotData[$member->id] = [
                // The pivot column is NOT NULL; TMDB occasionally omits or nulls it.
                'character' => $cast_member->character ?? '',
                'order' => $cast_member->order,
            ];
        }

        $model->cast_members()->attach($pivotData);
    }
}
